import axios from 'axios'

export default axios.create({
  baseURL: `https://api.covid19api.com/`,
  headers: {
    'X-Access-Token': '5cf9dfd5-3449-485e-b5ae-70a60e997864',
  },
})

export const data_obat = [
  {
    id: '1',
    img:
      'https://d2qjkwm11akmwu.cloudfront.net/products/46265_25-6-2020_11-27-43.jpeg',
    name: 'HALOWELL C 500 MG 30 TABLET',
    desc:
      'HALOWELL C 500 MG TABLET merupakan suplemen berbentuk tablet yang mengandung Vitamin C. Suplemen ini digunakan untuk memenuhi kebutuhan harian vitamin C tubuh',
    price: 20000,
    aturan: 'Sehari 1 Kali 1 Tablet dikonsumsi setelah makan',
    total: 1,
  },
  {
    id: '2',
    img: 'https://d2qjkwm11akmwu.cloudfront.net/products/images/9008.jpg',
    name: 'SURBEX-Z 6 TABLET',
    desc:
      'SURBEX-Z TABLET merupakan suplemen yang mengandung multivitamin dan mineral. Suplemen ini digunakan untuk membantu memelihara daya tahan tubuh.',
    price: 20300,
    aturan: '1 Tablet perhari dikonsumsi setelah makan',
    total: 1,
  },
  {
    id: '3',
    img:
      'https://d2qjkwm11akmwu.cloudfront.net/products/435892_7-9-2020_17-22-43.jpeg',
    name: 'IMBOOST FORCE 10 KAPLET',
    desc:
      'IMBOOST FORCE TABLET merupakan produk suplemen kesehatan untuk meningkatkan daya tahan tubuh',
    price: 65000,
    aturan: '1 Table 3 kali perhari dikonsumsi setelah makan',
    total: 1,
  },
  {
    id: '4',
    img:
      'https://d2qjkwm11akmwu.cloudfront.net/products/194480_20-4-2020_11-26-23.jpeg',
    name: 'LIANHUA QINGWEN 24 KAPSUL',
    desc:
      'LIANHUA QINGWEN KAPSUL merupakan produk herbal China yang mengandung kombinasi dari 13 tanaman herbal. Produk ini digunakan untuk membantu meringankan gejala influenza, seperti: panas dalam, demam, nyeri sendi / pegal linu, hidung tersumbat dan beringus, sakit kepala, batuk dan tenggorokan kering.',
    price: 60000,
    aturan: 'Sehari 3 kali 4 kapsul dikonsumsi setelah makan',
    total: 1,
  },
  {
    id: '5',
    img:
      'https://d2qjkwm11akmwu.cloudfront.net/products/645427_13-10-2020_16-46-54.jpeg',
    name: 'IMBOOST 10 TABLET',
    desc:
      'IMBOOST TABLET merupakan suplemen dengan kandungan Echinacea purpurea herb dry extract dan Zn Piccolinate dalam bentuk tablet salut selaput. Suplemen ini digunakan untuk meningkatkan daya tahan tubuh yang berfungsi untuk mencegah dari sakit dan mempercepat penyembuhan.',
    price: 36300,
    aturan: '1 Tablet, 2-3 kali perhari dikonsumsi setelah makan',
    total: 1,
  },
  {
    id: '6',
    img:
      'https://d2qjkwm11akmwu.cloudfront.net/products/573015_13-3-2019_13-29-36.jpg',
    name: 'ASTRIA 4 MG 12 KAPSUL',
    desc:
      'ASTRIA 4 MG 12 KAPSUL merupakan suplemen yang mengandung zat aktif Asthaxanthin. Suplemen ini digunaka untuk membantu memelihara kesehatan.',
    price: 60000,
    aturan: '1 Kapsul lunak perhari dikonsumsi setelah makan',
    total: 1,
  },
  {
    id: '7',
    img:
      'https://d2qjkwm11akmwu.cloudfront.net/products/570514_21-3-2020_19-49-33.jpg',
    name: 'CDR EFFERVESCENT 10 TABLET',
    desc:
      'CDR EFFERVESCENT 10 TABLET merupakan suplemen vitamin dan mineral yang digunakan untuk memenuhi kebutuhan tubuh untuk membantu mengembalikan kondisi kesehatan selama kehamilan dan menyusui, masa pertumbuhan, pemulihan, malnutrisi dan malabsorbsi. Suplemen ini juga dapat digunakan untuk membantu perkembangan tulang dan gigi.',
    price: 36500,
    aturan:
      '1 tablet effervescent per hari, Dilarutkan dalam 1 gelas air minum dan di minum segera setelah dilarutkan.',
    total: 1,
  },
  {
    id: '8',
    img: 'https://d2qjkwm11akmwu.cloudfront.net/products/images/9284.jpg',
    name: 'VITACIMIN 500 MG RASA LEMON 2 TABLET',
    desc:
      'VITACIMIN merupakan suplemen kesehatan dengan kandungan Ascorbic acid atau Vitamin C dalam bentuk tablet hisap. Suplemen ini digunakan untuk membantu memenuhi kebutuhan vitamin c harian, serta membantu menjaga daya tahan tubuh.',
    price: 1700,
    aturan: 'Sehari 1 - 2 Tablet, Dianjurkan untuk dikonsumsi setelah makan',
    total: 1,
  },
]

export const data_dokter_1 = [
  {
    id: '1',
    name: 'dr. Elizabeth Kosasih',
    rate: '5',
    total: '20',
    exp: '2',
    img:
      'https://d1ojs48v3n42tp.cloudfront.net/personnels/399827_26-6-2020_12-41-47.jpeg',
    type: 'Dokter Umum',
  },

  {
    id: '2',
    name: 'dr. Yonatan Kristiono Gunadi',
    rate: '5',
    total: '30',
    exp: '9',
    img:
      'https://d1ojs48v3n42tp.cloudfront.net/personnels/862901_28-6-2019_19-42-12.png',
    type: 'Dokter Umum',
  },

  {
    id: '3',
    name: 'dr. Annisa Oktantiani',
    rate: '5',
    total: '25',
    exp: '5',
    img:
      'https://d1ojs48v3n42tp.cloudfront.net/personnels/453179_30-9-2020_15-58-18.jpeg',
    type: 'Dokter Umum',
  },
]

export const data_dokter_2 = [
  {
    id: '4',
    name: 'dr. Bryan John Junior',
    rate: '5',
    total: '32',
    exp: '4',
    img:
      'https://d1ojs48v3n42tp.cloudfront.net/personnels/301297_21-9-2020_16-16-57.png',
    type: 'Dokter Umum',
  },

  {
    id: '5',
    name: 'dr. Cokorda Gede Sananjaya',
    rate: '5',
    total: '30',
    exp: '2',
    img:
      'https://d1ojs48v3n42tp.cloudfront.net/personnels/48375_2-10-2020_9-48-48.png',
    type: 'Dokter Umum',
  },

  {
    id: '6',
    name: 'dr. Cindi Nofita Sari',
    rate: '5',
    total: '15',
    exp: '3',
    img:
      'https://d1ojs48v3n42tp.cloudfront.net/personnels/259030_21-8-2020_19-27-23.png',
    type: 'Dokter Umum',
  },
]

export const hospital_api = [
  {
    name: 'RS UMUM DAERAH  DR. ZAINOEL ABIDIN',
    address: 'JL. TGK DAUD BEUREUEH, NO. 108 B. ACEH',
    region: 'KOTA BANDA ACEH, ACEH',
    phone: '(0651) 34565',
    province: 'Aceh',
    maps: 'https://goo.gl/maps/ZdD5PcQGw13xDhQK7',
  },
  {
    name: 'RS UMUM DAERAH CUT MEUTIA ',
    address: 'JL. BANDA ACEH-MEDAN KM.6 BUKET RATA LHOKSEUMAWE',
    region: 'KOTA LHOKSEUMAWE, ACEH',
    phone: '(0645) 46334',
    province: 'Aceh',
    maps: 'https://g.page/rsu-cut-meutia?share',
  },
  {
    name: 'RSUP SANGLAH',
    address: 'JL. DIPONEGORO DENPASAR BALI',
    region: 'KOTA DENPASAR, BALI',
    phone: '(0361) 227912',
    province: 'Bali',
    maps: 'https://goo.gl/maps/uq2w69trArkiEmp19',
  },
  {
    name: 'RS UMUM DAERAH KAB. BULELENG',
    address: 'JL. NGURAH RAI 30 SINGARAJA',
    region: 'BULELENG, BALI',
    phone: '(0362) 22046',
    province: 'Bali',
    maps: 'https://goo.gl/maps/Y7pX7cu5ofRA1c4WA',
  },
  {
    name: 'RS UMUM DAERAH SANJIWANI GIANYAR',
    address: 'JL. CIUNG WENARA NO.2 GIANYAR',
    region: 'GIANYAR, BALI',
    phone: '(0361) 943049',
    province: 'Bali',
    maps: 'https://goo.gl/maps/hWyLqfSnwv1DWqhH9',
  },
  {
    name: 'RS UMUM DAERAH TABANAN',
    address: 'JL. PAHLAWAN NO. 14 TABANAN',
    region: 'TABANAN, BALI',
    phone: '(0361) 811027',
    province: 'Bali',
    maps: 'https://goo.gl/maps/zBC26jcrVi4FfSmp7',
  },
  {
    name: 'RS UMUM DAERAH KABUPATEN TANGERANG',
    address: 'JL. A YANI NO. 9 TANGERANG, KOTA TANGERANG',
    region: 'TANGERANG, BANTEN',
    phone: '(021) 5523507 / (021)  5512948 / (021) 5513709',
    province: 'Banten',
    maps: 'https://goo.gl/maps/VNwXiQWmuFBeUbeQ7',
  },
  {
    name: 'RS UMUM DAERAH DR. DRAJAT PRAWIRANEGARA',
    address: 'JL. TGK DAUD BEUREUEH, NO. 108 B. ACEH',
    region: 'TANGERANG, BANTEN',
    phone: null,
    province: 'Banten',
    maps: 'https://goo.gl/maps/3QZZqWuo5rGcAmQ69',
  },
  {
    name: 'RS UMUM DAERAH DR. M. YUNUS BENGKULU',
    address:
      'JL. BHAYANGKARA, SIDOMULYO, KEC. GADING CEMP., KOTA BENGKULU, BENGKULU 38211',
    region: 'KOTA BENGKULU, BENGKULU',
    phone: '(0736) 52004',
    province: 'Bengkulu',
    maps: 'https://goo.gl/maps/8Vu6u2psJHMjZDA2A',
  },
  {
    name: 'RS UMUM DAERAH ARGA MAKMUR',
    address:
      'JL. SITI KHODIJAH NO.8, KALI, ARMA JAYA, KABUPATEN BENGKULU UTARA, BENGKULU 38611',
    region: 'BENGKULU UTARA, BENGKULU',
    phone: '(0737) 521118',
    province: 'Bengkulu',
    maps: 'https://goo.gl/maps/eHg7PXdgm35KHnmY8',
  },
  {
    name: 'RS UMUM DAERAH HASANUDDIN DAMRAH MANNA',
    address:
      'JL. RAYA PADANG PANJANG, PAGAR DEWA, KOTA MANNA, KABUPATEN BENGKULU SELATAN, BENGKULU 38515',
    region: 'BENGKULU SELATAN, BENGKULU',
    phone: '0853-8163-7684',
    province: 'Bengkulu',
    maps: 'https://goo.gl/maps/mc5Hunggmqte31cg7',
  },
  {
    name: 'RS UMUM DAERAH PANEMBAHAN SENOPATI',
    address: 'JL DR. WAHIDIN SUDIRO HUSODO BANTUL',
    region: 'BANTUL, DAERAH ISTIMEWA YOGYAKARTA',
    phone: '(0274) 367381',
    province: 'DI Yogyakarta',
    maps: 'https://goo.gl/maps/hXRHzBtyDNmktazA7',
  },
  {
    name: 'RS UMUM DAERAH WATES',
    address: 'JL TENTARA PELAJAR KM.1 NO.5 WATES KULON PROGO',
    region: 'KULON PROGO, DAERAH ISTIMEWA YOGYAKARTA',
    phone: '(0274) 773169',
    province: 'DI Yogyakarta',
    maps: 'https://goo.gl/maps/MQrK8VUdwVC69YJv9',
  },
  {
    name: 'RS UMUM DAERAH KOTA YOGYAKARTA',
    address:
      'JL. KI AGENG PEMANAHAN NO.1, SOROSUTAN, KEC. UMBULHARJO, KOTA YOGYAKARTA, DAERAH ISTIMEWA YOGYAKARTA 55162',
    region: 'KOTA YOGYAKARTA, DAERAH ISTIMEWA YOGYAKARTA',
    phone: '(0274) 371195',
    province: 'DI Yogyakarta',
    maps: 'https://goo.gl/maps/bGgAc9cokkbABV976',
  },
  {
    name: 'RSUP DR. SARDJITO',
    address: 'JL KESEHATAN NO.1 SEKIP YOGYAKARTA',
    region: 'SLEMAN, DAERAH ISTIMEWA YOGYAKARTA',
    phone: '(0274) 631190',
    province: 'DI Yogyakarta',
    maps: 'https://goo.gl/maps/cT3iHnUrwigGF4xg9',
  },
  {
    name: 'RS UMUM AL DR MINTOHARJO',
    address: 'JL. BENDUNGAN HILIR 17 JAKPUS',
    region: 'JAKARTA PUSAT, DKI JAKARTA',
    phone: '(021) 5703081',
    province: 'DKI Jakarta',
    maps: 'https://goo.gl/maps/CV1w6gEC6NbqR7UA9',
  },
  {
    name: 'RS UMUM PAD GATOT SOEBROTO',
    address: 'JL. DR. ABDUL  RAHMAN SALEH NO. 24  JAKARTA PUSAT',
    region: 'JAKARTA PUSAT, DKI JAKARTA',
    phone: '(021) 3441008',
    province: 'DKI Jakarta',
    maps: 'https://goo.gl/maps/v1awpYqqcJHEkKgz5',
  },
  {
    name: 'RS UMUM BHAYANGKARA TK. I R.SAID SUKANTO',
    address: 'JL. RAYA BOGOR KRAMAT JATI,JAKARTA TIMUR',
    region: 'JAKARTA TIMUR, DKI JAKARTA',
    phone: '(021) 8093288',
    province: 'DKI Jakarta',
    maps: 'https://goo.gl/maps/Ryct5YZvAZSvBSqP7',
  },
  {
    name: 'RSUP PERSAHABATAN',
    address: 'JL. PERSAHABATAN RAYA NO. 1,JAKTIM',
    region: 'JAKARTA TIMUR, DKI JAKARTA',
    phone: '(021) 4891708',
    province: 'DKI Jakarta',
    maps: 'https://goo.gl/maps/4q9QhM1ZhEWfKm5V6',
  },
  {
    name: 'RS PENYAKIT INFEKSI PROF. DR. SULIANTI SAROSO',
    address: 'JL. BARU SUNTER PERMAI RAYA JAKARTA UTARA',
    region: 'JAKARTA UTARA, DKI JAKARTA',
    phone: '(021) 6506559',
    province: 'DKI Jakarta',
    maps: 'https://goo.gl/maps/3jRtPwvDM2fuonAw6',
  },
  {
    name: 'RSUP FATMAWATI',
    address: 'JL. RS FATMAWATI CILANDAK,JAKSEL',
    region: 'JAKARTA SELATAN, DKI JAKARTA',
    phone: '(021) 7501524',
    province: 'DKI Jakarta',
    maps: 'https://goo.gl/maps/4RhfNozX5t6sp6yC7',
  },
  {
    name: 'RS UMUM DAERAH PASAR MINGGU',
    address:
      'JL. TB. SIMATUPANG NO. 1 KELURAHAN RAGUNAN, KECAMATAN PASAR MINGGU - JAKARTA SELATAN',
    region: 'JAKARTA SELATAN, DKI JAKARTA',
    phone: '(021) 29059999',
    province: 'DKI Jakarta',
    maps: 'https://goo.gl/maps/s4yJDtR5CuDPhTXRA',
  },
  {
    name: 'RS UMUM DAERAH CENGKARENG',
    address: 'JL.KAMAL RAYA BUMI CENGKARENG INDAH CENGKARENG TIMUR',
    region: 'JAKARTA BARAT, DKI JAKARTA',
    phone: null,
    province: 'DKI Jakarta',
    maps: 'https://goo.gl/maps/rvTSsJ1C5Z5juJfA9',
  },
  {
    name: 'RS UMUM DAERAH PROF DR. H. ALOEI SABOE',
    address:
      'JL. PROFESOR DR. H. ALOEI SABOE, WONGKADITI, KOTA UTARA, KOTA GORONTALO, GORONTALO 96115',
    region: 'GORONTALO, GORONTALO',
    phone: '0435 821924',
    province: 'Gorontalo',
    maps:
      'https://www.google.com/maps/dir/?api=1&destination=0.55491860,123.08411110',
  },
  {
    name: 'RS UMUM DAERAH RADEN MATTAHER JAMBI',
    address:
      'JL. LETJEN SUPRAPTO NO.31, TELANAIPURA, KEC. TELANAIPURA, KOTA JAMBI, JAMBI 36361',
    region: 'MUARO JAMBI, JAMBI',
    phone: '(0741) 61692',
    province: 'Jambi',
    maps: 'https://goo.gl/maps/xWheky75pMv5cATS6',
  },
  {
    name: 'RS PARU DR. H. A. ROTINSULU',
    address: 'JL. BUKIT JARIAN NO. 40 BANDUNG',
    region: 'BANDUNG, JAWA BARAT',
    phone: null,
    province: 'Jawa Barat',
    maps: 'https://goo.gl/maps/aPeTsem1DipKhEM29',
  },
  {
    name: 'RS UMUM PUSAT DR. HASAN SADIKIN',
    address: 'JL. PASTEUR NO. 38 BANDUNG',
    region: 'BANDUNG, JAWA BARAT',
    phone: null,
    province: 'Jawa Barat',
    maps: 'https://goo.gl/maps/kQLWR5ENmqHCyamn9',
  },
  {
    name: 'RS UMUM DAERAH DR. SLAMET GARUT',
    address: 'JL. RUMAH SAKIT NO.12 GARUT',
    region: 'GARUT, JAWA BARAT',
    phone: '(0262) 232720',
    province: 'Jawa Barat',
    maps: 'https://goo.gl/maps/K3TQ3UmCzb8a1jLm6',
  },
  {
    name: 'RS UMUM TK II DUSTIRA',
    address: 'JL. DR. DUSTIRA NO.1 KEL. BAROS KEC. CIMAHI TENGAH',
    region: 'KOTA CIMAHI, JAWA BARAT',
    phone: '(022) 6652207',
    province: 'Jawa Barat',
    maps: 'https://goo.gl/maps/XePbuQsk5LaJ29KZ8',
  },
  {
    name: 'RS PARU DR. M. GOENAWAN PARTOWIDIGDO',
    address: 'JL. RAYA PUNCAK KM.83, PO BOX 28 CISARUA BOGOR 16750',
    region: 'BOGOR, JAWA BARAT',
    phone: '0251-8253630',
    province: 'Jawa Barat',
    maps: 'https://goo.gl/maps/k8wY8pd5Ww8bn8hM9',
  },
  {
    name: 'RS UMUM DAERAH  R SYAMSUDIN SH',
    address: 'JL. RUMAH SAKIT NO. 1 KOTA SUKABUMI',
    region: 'SUKABUMI, JAWA BARAT',
    phone: null,
    province: 'Jawa Barat',
    maps: 'https://goo.gl/maps/cyyp6sr5bvw8hsb77',
  },
  {
    name: 'RS UMUM DAERAH GUNUNG JATI',
    address: 'JL. KESAMBI NO.56 CIREBON - 45134',
    region: 'CIREBON, JAWA BARAT',
    phone: null,
    province: 'Jawa Barat',
    maps: 'https://goo.gl/maps/6fX3P5xLMzZ9hmy17',
  },
  {
    name: 'RS UMUM DAERAH KAB. INDRAMAYU',
    address: 'JL. MURAH NARA NO. 7 SINDANG INDRAMAYU',
    region: 'INDRAMAYU, JAWA BARAT',
    phone: '(0234) 272655',
    province: 'Jawa Barat',
    maps: 'https://goo.gl/maps/kNnTdpqJreLgpGz29',
  },
  {
    name: 'RS UMUM DAERAH K.R.M.T WONGSONEGORO',
    address: 'JL. FATMAWATI RAYA NO.1',
    region: 'SEMARANG, JAWA TENGAH',
    phone: '(024) 6711500',
    province: 'Jawa Tengah',
    maps: 'https://g.page/Rswongsonegoro?share',
  },
  {
    name: 'RS UMUM PUSAT DR. KARIADI',
    address: 'JL. DR. SOETOMO NO.16,SEMARANG',
    region: 'SEMARANG, JAWA TENGAH',
    phone: null,
    province: 'Jawa Tengah',
    maps: 'https://goo.gl/maps/PaRHA8SWEQizLMFh9',
  },
  {
    name: 'RS UMUM DAERAH KARDINAH',
    address:
      'JALAN AIP JL. KS. TUBUN NO.2, KEJAMBON, KEC. TEGAL TIM., KOTA TEGAL, JAWA TENGAH 52124',
    region: 'TEGAL, JAWA TENGAH',
    phone: '(0283) 350477',
    province: 'Jawa Tengah',
    maps: 'https://goo.gl/maps/HiQemp1e8BscCYgdA',
  },
  {
    name: 'RS UMUM PUSAT DR. SOERADJI TIRTONEGORO',
    address: 'JL. KRT. SURAJI TIRTONEGORO NO.1, KLATEN',
    region: 'KLATEN, JAWA TENGAH',
    phone: null,
    province: 'Jawa Tengah',
    maps: 'https://goo.gl/maps/m3ujdEugdYD4dBHv8',
  },
  {
    name: 'RS UMUM DAERAH DR. LOEKMONO HADI',
    address: 'JL. DR. LUKMONOHADI NO.19,KUDUS',
    region: 'KUDUS, JAWA TENGAH',
    phone: null,
    province: 'Jawa Tengah',
    maps: 'https://goo.gl/maps/tBvH5K1LynS6tfLp7',
  },
  {
    name: 'RS UMUM DAERAH DR. SOESELO SLAWI',
    address:
      'JL. DR. SOETOMO NO.63, SLAWI KULON, KEC. SLAWI, TEGAL, JAWA TENGAH 52419',
    region: 'TEGAL, JAWA TENGAH',
    phone: '(0283) 491016',
    province: 'Jawa Tengah',
    maps: 'https://goo.gl/maps/4AgXHDLyN8Tmxvd38',
  },
  {
    name: 'RS UMUM DAERAH KRATON',
    address: 'JL. DR SUTOMO NO. 42 BATANG',
    region: 'PEKALONGAN, JAWA TENGAH',
    phone: null,
    province: 'Jawa Tengah',
    maps: 'https://g.page/rsudkraton?share',
  },
  {
    name: 'RS UMUM DAERAH  DR. H. SOEWONDO KENDAL',
    address: 'JL. LAUT NO. 21, KENDAL',
    region: 'KENDAL, JAWA TENGAH',
    phone: null,
    province: 'Jawa Tengah',
    maps: 'https://goo.gl/maps/9fUJykJgKCba5fjj6',
  },
  {
    name: 'RS UMUM DAERAH DR. MOEWARDI SURAKARTA',
    address: 'JL. KOL SUTARTO 132,SURAKARTA',
    region: 'KOTA SURAKARTA, JAWA TENGAH',
    phone: null,
    province: 'Jawa Tengah',
    maps: 'https://g.page/RSUD-Dr-Moewardi?share',
  },
  {
    name: 'RS UMUM DAERAH TIDAR',
    address: 'JL. TIDAR NO.30 A, KOTA MAGELANG',
    region: 'MAGELANG, JAWA TENGAH',
    phone: null,
    province: 'Jawa Tengah',
    maps: 'https://goo.gl/maps/jqdkFq6bZHzAtv7f8',
  },
  {
    name: 'RSUD BANYUMAS',
    address: 'JL. RUMAH SAKIT NO.1 BANYUMAS',
    region: 'BANYUMAS, JAWA TENGAH',
    phone: null,
    province: 'Jawa Tengah',
    maps: 'https://g.page/rsudbanyumas?share',
  },
  {
    name: 'RS PARU DR. ARIO WIRAWAN',
    address: 'JL. HASANUDIN NO.806,SALATIGA',
    region: 'KOTA SALATIGA, JAWA TENGAH',
    phone: null,
    province: 'Jawa Tengah',
    maps: 'https://goo.gl/maps/ZVPxExhDTRUexvj68',
  },
  {
    name: 'RS UMUM DAERAH PROF DR. MARGONO SOEKARJO',
    address: 'JL. DR GUMBREG NO. 1 PURWOKERTO',
    region: 'BANYUMAS, JAWA TENGAH',
    phone: null,
    province: 'Jawa Tengah',
    maps: 'https://goo.gl/maps/NQL7JQCXmd5Ec1Y79',
  },
  {
    name: 'RS UNIVERSITAS AIRLANGGA',
    address: 'KAMPUS C UNIVERSITAS AIRLANGGA, MULYOREJO, SURABAYA',
    region: 'KOTA SURABAYA, JAWA TIMUR',
    phone: '0813-3235-5540',
    province: 'Jawa Timur',
    maps: 'https://goo.gl/maps/Zgt45wpuVXtxmfWh7',
  },
  {
    name: 'RS UMUM DAERAH DR. SOETOMO',
    address: 'JL. MAYJEND. PROF. DR. MOESTOPO NO. 6 - 8 SURABAYA, JAWA TIMUR',
    region: 'KOTA SURABAYA, JAWA TIMUR',
    phone: '(031) 5501078',
    province: 'Jawa Timur',
    maps: 'https://goo.gl/maps/aURt6cCn27eC59hE8',
  },
  {
    name: 'RS UMUM DAERAH DR. SOEDONO MADIUN',
    address: 'JL. DR. SOETOMO 59, MADIUN',
    region: 'KOTA MADIUN, JAWA TIMUR',
    phone: '(0351) 454657',
    province: 'Jawa Timur',
    maps: 'https://g.page/rssoedono?share',
  },
  {
    name: 'RS UMUM DAERAH DR. SAIFUL ANWAR',
    address: 'JL. JAKSA AGUNG SUPRAPTO NO.2 MALANG',
    region: 'MALANG, JAWA TIMUR',
    phone: '(0341) 362101',
    province: 'Jawa Timur',
    maps: 'https://goo.gl/maps/iPqk49rXmD8bEpTTA',
  },
  {
    name: 'RS UMUM DAERAH DR. R. KOESMA TUBAN',
    address: 'JL. DR. WAHIDIN SUDIRO HUSODO NO. 800',
    region: 'TUBAN, JAWA TIMUR',
    phone: '(0356) 321010',
    province: 'Jawa Timur',
    maps: 'https://goo.gl/maps/1WKFiE9hb6AaeWyf6',
  },
  {
    name: 'RS UMUM DAERAH DR. ISKAK TULUNGAGUNG',
    address: 'JL. DR. WAHIDIN SUDIRO HUSODO TULUNGAGUNG',
    region: 'TULUNGAGUNG, JAWA TIMUR',
    phone: '(0355) 322609',
    province: 'Jawa Timur',
    maps: 'https://g.page/rsudiskak?share',
  },
  {
    name: 'RS UMUM DAERAH SIDOARJO',
    address: 'JALAN MOJOPAHIT NO. 667 SIDOARJO',
    region: 'SIDOARJO, JAWA TIMUR',
    phone: '(031) 8961649',
    province: 'Jawa Timur',
    maps: 'https://g.page/rsudsidoarjo?share',
  },
  {
    name: 'RS UMUM DAERAH BLAMBANGAN',
    address: 'JL. LETKOL ISTIQLAH NO. 49 BANYUWANGI',
    region: 'BANYUWANGI, JAWA TIMUR',
    phone: '(0333) 421118',
    province: 'Jawa Timur',
    maps: 'https://g.page/rsudblambangan?share',
  },
  {
    name: 'RS UMUM DAERAH DR. SOEBANDI',
    address: 'JL. DR. SOEBANDI NO.124, JEMBER',
    region: 'JEMBER, JAWA TIMUR',
    phone: '(0331) 487441',
    province: 'Jawa Timur',
    maps: 'https://g.page/cilok-manggar?share',
  },
  {
    name: 'RS UMUM DAERAH KABUPATEN KEDIRI',
    address: 'JL. PAHLAWAN KUSUMA BANGSA NO. 1 PARE',
    region: 'KEDIRI, JAWA TIMUR',
    phone: '(0354) 391718',
    province: 'Jawa Timur',
    maps: 'https://goo.gl/maps/V2GqEitsUU16uvRF8',
  },
  {
    name: 'RS UMUM DAERAH DR. R. SOSODORO DJATIKOESOEMO',
    address: 'JL. VETERAN NO 36, BOJONEGORO',
    region: 'BOJONEGORO, JAWA TIMUR',
    phone: '(0353) 3412133',
    province: 'Jawa Timur',
    maps: 'https://goo.gl/maps/ViSamdcsJg6UCEfh8',
  },
  {
    name: 'RS UMUM DAERAH DR. SOEDARSO PONTIANAK',
    address: 'JL. DR. SOEDARSO NO.1 PONTIANAK',
    region: 'KOTA PONTIANAK, KALIMANTAN BARAT',
    phone: '(0561) 737701',
    province: 'Kalimantan Barat',
    maps: 'https://goo.gl/maps/TfQKa4KUnFNZQmWk6',
  },
  {
    name: 'RS UMUM DAERAH ADE MUHAMMAD DJOEN SINTANG',
    address: 'JL. PATIMURA DAN JL.YC OEVANG OERAY SINTANG',
    region: 'SINTANG, KALIMANTAN BARAT',
    phone: '(0565) 21002',
    province: 'Kalimantan Barat',
    maps: 'https://goo.gl/maps/oPQo7FhKQCjLgg9v6',
  },
  {
    name: 'RS UMUM DAERAH DR. AGOESDJAM KETAPANG',
    address: 'JL. PANJAITAN NO.51 KETAPANG',
    region: 'KETAPANG, KALIMANTAN BARAT',
    phone: '(0534) 3037239',
    province: 'Kalimantan Barat',
    maps: 'https://goo.gl/maps/7TmZBXrSWwx41aGUA',
  },
  {
    name: 'RS UMUM DAERAH DR. ABDUL AZIZ SINGKAWANG',
    address: 'JL. DR SOETOMO NO. 28, SINGKAWANG',
    region: 'KOTA SINGKAWANG, KALIMANTAN BARAT',
    phone: null,
    province: 'Kalimantan Barat',
    maps: 'https://g.page/rsudaa?share',
  },
  {
    name: 'RS UMUM DAERAH ULIN BANJARMASIN',
    address: 'JL. JEN A YANI NO.43, BANJARMASIN KALIMANTAN SELATAN',
    region: 'KOTA BANJARMASIN, KALIMANTAN SELATAN',
    phone: '(0511) 3252180',
    province: 'Kalimantan Selatan',
    maps: 'https://goo.gl/maps/57yNZhejTaZeH4649',
  },
  {
    name: 'RS UMUM DAERAH H. BOEJASIN PELAIHARI',
    address: 'JL. HADJI BOEJASIN NO.68 KAB. TANAH LAUT',
    region: 'TANAH LAUT, KALIMANTAN SELATAN',
    phone: '(0512) 21083',
    province: 'Kalimantan Selatan',
    maps: 'https://goo.gl/maps/tnhHELWjskV8AorKA',
  },
  {
    name: 'RS UMUM DAERAH DR DORIS SYLVANUS PALANGKA RAYA',
    address: 'JL. TAMBUN BUNGAI NO.4 PALANGKARAYA',
    region: 'MURUNG RAYA, KALIMANTAN TENGAH',
    phone: '(0536) 3224695',
    province: 'Kalimantan Tengah',
    maps: 'https://goo.gl/maps/zsn6L4NTBYh1MMtXA',
  },
  {
    name: 'RS UMUM DAERAH SULTAN IMANUDDIN',
    address: 'JL. SUTAN SYAHRIR NO 17 PANGKALAN BUN',
    region: 'KOTAWARINGIN BARAT, KALIMANTAN TENGAH',
    phone: '(0532) 21404',
    province: 'Kalimantan Tengah',
    maps: 'https://goo.gl/maps/hJsuMdbP8hYEuXuSA',
  },
  {
    name: 'RS UMUM DAERAH DR MURJANI SAMPIT',
    address: 'JL. H M ARSYAD NO. 65 SAMPIT',
    region: 'BARITO TIMUR, KALIMANTAN TENGAH',
    phone: '(0531) 21010',
    province: 'Kalimantan Tengah',
    maps: 'https://goo.gl/maps/m38Tp4MijiKagJj86',
  },
  {
    name: 'RS UMUM DAERAH ABDUL WAHAB SJAHRANIE',
    address:
      'JL. PALANG MERAH NO.1, SIDODADI, KEC. SAMARINDA ULU, KOTA SAMARINDA, KALIMANTAN TIMUR 75123',
    region: 'KOTA SAMARINDA, KALIMANTAN TIMUR',
    phone: '(0541) 738118',
    province: 'Kalimantan Timur',
    maps: 'https://goo.gl/maps/42nPfGSVZPQVKmoK8',
  },
  {
    name: 'RS UMUM DAERAH TAMAN HUSADA',
    address:
      'JL. LETJEN S. PARMAN NO.1, BELIMBING, BONTANG BAR., KOTA BONTANG, KALIMANTAN TIMUR 75331',
    region: 'KOTA BONTANG, KALIMANTAN TIMUR',
    phone: '(0548) 23000',
    province: 'Kalimantan Timur',
    maps: 'https://goo.gl/maps/epxJiErnJCubnXbx8',
  },
  {
    name: 'RS UMUM DAERAH DR. KANUJOSO DJATIWIBOWO',
    address: 'JL. M.T. HARYONO RING ROAD BALIKPAPAN NO.656',
    region: 'KOTA BALIKPAPAN, KALIMANTAN TIMUR',
    phone: '(0542) 873901',
    province: 'Kalimantan Timur',
    maps: 'https://goo.gl/maps/wYGCMZyvVMagRQ4W7',
  },
  {
    name: 'RS UMUM DAERAH AJI MUHAMMAD PARIKESIT',
    address: 'JL. RATU AGUNG NO. 1 TENGGARONG SEBERANG',
    region: 'KUTAI KARTANEGARA, KALIMANTAN TIMUR',
    phone: '(0541) 661015',
    province: 'Kalimantan Timur',
    maps: 'https://g.page/RSAMP?share',
  },
  {
    name: 'RS UMUM DAERAH PANGLIMA SEBAYA',
    address: 'JL. KUSUMA BANGSA KM.5 TANAH GROGOT',
    region: 'PASER, KALIMANTAN TIMUR',
    phone: '0852-4743-3000',
    province: 'Kalimantan Timur',
    maps: 'https://goo.gl/maps/TL5ELEFdSMBwR5Q2A',
  },
  {
    name: 'RS UMUM DAERAH TANJUNG SELOR',
    address:
      'JL CENDRAWASIH KEL TANJUNG SELOR HILIR, KEC TANJUNG SELOR KAB BULUNGAN',
    region: 'BULUNGAN, KALIMANTAN UTARA',
    phone: '(0552) 21118',
    province: 'Kalimantan Utara',
    maps: 'https://goo.gl/maps/WkMvw7ew5CCicYyr5',
  },
  {
    name: 'RS UMUM KOTA TARAKAN',
    address:
      'JL. AKI BABU RT 01 KELURAHAN KARANG HARAPAN KECAMATAN TARAKAN BARAT KOTA TARAKAN PROVINSI KALIMANTAN',
    region: 'KOTA TARAKAN, KALIMANTAN UTARA',
    phone: '(0551) 21166',
    province: 'Kalimantan Utara',
    maps: 'https://goo.gl/maps/s9KZyCfrPkaS1sHy5',
  },
  {
    name: 'RS UMUM DAERAH DEPATI HAMZAH',
    address:
      'JL. SOEKARNO HATTA, BUKITBESAR, KEC. GIRIMAYA, KOTA PANGKAL PINANG, KEPULAUAN BANGKA BELITUNG 33684',
    region: 'KOTA PANGKALPINANG, KEPULAUAN BANGKA BELITUNG',
    phone: '(0717) 438660',
    province: 'Kep. Bangka Belitung',
    maps: 'https://goo.gl/maps/mgTerrmJoZPParKr9',
  },
  {
    name: 'RS UMUM DAERAH DR. H. MARSIDI JUDONO',
    address:
      'JL. JEND. SUDIRMAN KM.5,5, AIK RAYAK, TJ. PANDAN, KABUPATEN BELITUNG, KEPULAUAN BANGKA BELITUNG 33411',
    region: 'BELITUNG, KEPULAUAN BANGKA BELITUNG',
    phone: '(0719) 22190',
    province: 'Kep. Bangka Belitung',
    maps: 'https://goo.gl/maps/oLDyHFLt8ZaggJVC6',
  },
  {
    name: 'RS UMUM DAERAH PROVINSI KEPULAUAN RIAU TANJUNGPINA',
    address: 'JL. W.R SUPRATMAN NO. 100 KM. 8 TANJUNGPINANG KEPULAUAN RIAU',
    region: 'KOTA TANJUNGPINANG, KEPULAUAN RIAU',
    phone: null,
    province: 'Kep. Riau',
    maps: 'https://goo.gl/maps/RpzC9DB7zxXmEwow9',
  },
  {
    name: 'RS BADAN PENGUSAHAAN BATAM',
    address: 'JL. DR. CIPTO MANGUNKUSUMO NO.1,  SEKUPANG,BATAM',
    region: 'KOTA BATAM, KEPULAUAN RIAU',
    phone: '(0778) 322121',
    province: 'Kep. Riau',
    maps: 'https://goo.gl/maps/gD14sKjP6QHcUnv28',
  },
  {
    name: 'RS UMUM DAERAH EMBUNG FATIMAH KOTA BATAM',
    address:
      'JL. LETJEND SUPRAPTO NO.1-9, BUKIT TEMPAYAN, KEC. BATU AJI, KOTA BATAM, KEPULAUAN RIAU 29425',
    region: 'KOTA BATAM, KEPULAUAN RIAU',
    phone: '(0778) 364446',
    province: 'Kep. Riau',
    maps: 'https://goo.gl/maps/t8JMZreMp52nQSsk7',
  },
  {
    name: 'RS UMUM DAERAH MUHAMMAD SANI KABUPATEN KARIMUN',
    address:
      'JALAN POROS NO.1, HARJOSARI, TEBING, KABUPATEN KARIMUN, KEPULAUAN RIAU 29663',
    region: 'KARIMUN, KEPULAUAN RIAU',
    phone: '(0777) 327808',
    province: 'Kep. Riau',
    maps: 'https://goo.gl/maps/iAgiBgjSPrp2jVcJ7',
  },
  {
    name: 'RS UMUM DAERAH DR H ABDUL MOELOEK',
    address:
      'JL. DR. RIVAI NO.6, PENENGAHAN, KEC. TJ. KARANG PUSAT, KOTA BANDAR LAMPUNG, LAMPUNG 35112',
    region: 'KOTA BANDAR LAMPUNG, LAMPUNG',
    phone: '(0721) 703312',
    province: 'Lampung',
    maps: 'https://goo.gl/maps/CjQGuXJDHg7cKWAx7',
  },
  {
    name: 'RS UMUM DAERAH AHMAD YANI METRO',
    address: 'JL.JEND. A.YANI NO.13 KOTA METRO',
    region: 'KOTA METRO, LAMPUNG',
    phone: null,
    province: 'Lampung',
    maps: 'https://goo.gl/maps/2p7XnVyFe3JhQD4C9',
  },
  {
    name: 'RS UMUM DAERAH MAY JEN HM RYACUDU',
    address:
      'JL. JEND. SUDIRMAN NO.2, KOTA GAPURA, KOTABUMI, KABUPATEN LAMPUNG UTARA, LAMPUNG 34511',
    region: 'LAMPUNG UTARA, LAMPUNG',
    phone: '(0724) 22095',
    province: 'Lampung',
    maps: 'https://goo.gl/maps/jQ4EwFeYN2PEfUWw5',
  },
  {
    name: 'RS UMUM DAERAH DR. H. BOB BAZAR, SKM',
    address:
      'JL. LETTU ROHANI NO.14 B, KEDATON, KEC. KALIANDA, KABUPATEN LAMPUNG SELATAN, LAMPUNG 35551',
    region: 'LAMPUNG SELATAN, LAMPUNG',
    phone: '(0727) 322159',
    province: 'Lampung',
    maps: 'https://goo.gl/maps/BymYAUzqizUTzLkQ9',
  },
  {
    name: 'RS UMUM PUSAT DR. J. LEIMENA',
    address:
      'JALAN R. SUPRAPTO NO.123, RUMAH TIGA, TLK. AMBON, KOTA AMBON, MALUKU',
    region: 'KOTA AMBON, MALUKU',
    phone: null,
    province: 'Maluku',
    maps: 'https://goo.gl/maps/NaCh6sUyzhdauKPd8',
  },
  {
    name: 'RS UMUM DR. M. HAULUSSY AMBON',
    address:
      'JL. DR. KAYADOE, BENTENG, NUSANIWE, KEL BENTENG, NUSANIWE, KOTA AMBON, MALUKU',
    region: 'KOTA AMBON, MALUKU',
    phone: '(0911) 344871',
    province: 'Maluku',
    maps: 'https://goo.gl/maps/snhBtJ343gMvRsYy5',
  },
  {
    name: 'RS UMUM DAERAH DR. P. P. MAGRETTI SAUMLAKI',
    address: 'JL. MR. LATUHARHARI - SAUMLAKI',
    region: 'MALUKU TENGGARA BARAT, MALUKU',
    phone: null,
    province: 'Maluku',
    maps: 'https://goo.gl/maps/YdG9foCfYyv4pRH2A',
  },
  {
    name: 'RS UMUM DAERAH DR. H. CHASAN BOESOIRIE TERNATE',
    address:
      'JL. CEMPAKA, TANAH TINGGI BAR., TERNATE SEL., KOTA TERNATE, MALUKU UTARA',
    region: 'KOTA TERNATE, MALUKU UTARA',
    phone: '(0921) 3121281',
    province: 'Maluku Utara',
    maps: 'https://goo.gl/maps/koyU3PfdvKGx5JU48',
  },
  {
    name: 'RS UMUM DAERAH NTB',
    address: 'JL. PRABU RANGKASARI DASAN CERMEN',
    region: 'KOTA MATARAM, NUSA TENGGARA BARAT',
    phone: '(0370) 7502424',
    province: 'Nusa Tenggara Barat',
    maps: 'https://goo.gl/maps/wjPBQu5FcGBFCbXr7',
  },
  {
    name: 'RS UMUM DAERAH DR. R. SOEDJONO SELONG',
    address: 'JL. PROF M. YAMIN, SH. NO. 55 SELONG',
    region: 'LOMBOK TIMUR, NUSA TENGGARA BARAT',
    phone: '0376 21415',
    province: 'Nusa Tenggara Barat',
    maps: 'https://goo.gl/maps/t982yWJNXuTWcXHj6',
  },
  {
    name: 'RS UMUM BIMA',
    address: 'JL. LANGSAT NO. 1 RABA KOTA BIMA',
    region: 'BIMA, NUSA TENGGARA BARAT',
    phone: '(0374-43142)',
    province: 'Nusa Tenggara Barat',
    maps:
      'https://www.google.com/maps/dir/?api=1&destination=-8.45014630,118.73293980',
  },
  {
    name: 'RS H. L. MANAMBAI ABDULKADIR',
    address:
      'JL. LINTAS SUMBAWA-BIMA KM 5, SEKETENG, KEC. SUMBAWA, KABUPATEN SUMBAWA, NUSA TENGGARA BAR. 84316',
    region: 'SUMBAWA, NUSA TENGGARA BARAT',
    phone: '(0371) 2628078',
    province: 'Nusa Tenggara Barat',
    maps: 'https://goo.gl/maps/pcosS7PY4ZAtK2QCA',
  },
  {
    name: 'RS UMUM PROF DR WZ JOHANES',
    address: 'JL. DR MOCH HATTA NO. 19 KUPANG',
    region: 'KUPANG, NUSA TENGGARA TIMUR',
    phone: '(0380) 820331',
    province: 'Nusa Tenggara Timur',
    maps: 'https://goo.gl/maps/XF3ntDtErw1f6dWZ6',
  },
  {
    name: 'RS UMUM DAERAH DR TC HILLERS MAUMERE',
    address:
      'JL WAIRKLAU, NO. 1, 86113, KOTA BARU, ALOK TIM., KABUPATEN SIKKA, NUSA TENGGARA TIM.',
    region: 'SIKKA, NUSA TENGGARA TIMUR',
    phone: '0812-6115-3944 / 0380 - 21617',
    province: 'Nusa Tenggara Timur',
    maps: 'https://goo.gl/maps/TmRech7RtNtwkYYz9',
  },
  {
    name: 'RS UMUM DAERAH KOMODO',
    address:
      'DESA GOLO BILAS, KECAMATAN KOMODO, KABUPATEN MANGGARAI BARAT, NTT',
    region: 'MANGGARAI BARAT, NUSA TENGGARA TIMUR',
    phone: '0813-3705-5250',
    province: 'Nusa Tenggara Timur',
    maps:
      'https://www.google.com/maps/dir/?api=1&destination=-8.54568860,119.90747000',
  },
  {
    name: 'RS UMUM JAYAPURA',
    address:
      'JL. KESEHATAN NO.1, DOK II, BAYANGKARA, JAYAPURA UTARA, KOTA JAYAPURA, PAPUA',
    region: 'JAYAPURA, PAPUA',
    phone: '(0967) 533616 EXT. 533781',
    province: 'Papua',
    maps: 'https://goo.gl/maps/D6PLMLzaU2xzwZuT9',
  },
  {
    name: 'RS UMUM MERAUKE',
    address:
      'JL. SOEKARJO WIRYOPRANOTO NO.1, MARO, KEC. MERAUKE, KABUPATEN MERAUKE, PAPUA 99613',
    region: 'MERAUKE, PAPUA',
    phone: '(0971) 321124 EXT. 321125',
    province: 'Papua',
    maps: 'https://goo.gl/maps/rZA1E2kSkfw7s7fi8',
  },
  {
    name: 'RS UMUM NABIRE',
    address:
      'JL. R.E. MARTADINATA, SIRIWINI, KEC. NABIRE, KABUPATEN NABIRE, PAPUA 98816',
    region: 'NABIRE, PAPUA',
    phone: '(0984) 21845',
    province: 'Papua',
    maps: 'https://goo.gl/maps/17RNosMbtHmrqedV7',
  },
  {
    name: 'RS UMUM DAERAH MANOKWARI',
    address:
      'JL. SILIWANGI NO.1, MANOKWARI BAR., KABUPATEN MANOKWARI, PAPUA BAR. 98312',
    region: 'MANOKWARI, PAPUA BARAT',
    phone: '(0986) 215133',
    province: 'Papua Barat',
    maps: 'https://goo.gl/maps/B9qmfdQkVdMTqsfP7',
  },
  {
    name: 'RS UMUM DAERAH KABUPATEN SORONG',
    address: 'JL. KESEHATAN NO. 36 SORONG',
    region: 'SORONG, PAPUA BARAT',
    phone: '(0951) 321850',
    province: 'Papua Barat',
    maps: 'https://g.page/Rsud-Kabupaten-Sorong?share',
  },
  {
    name: 'RS UMUM DAERAH  ARIFIN ACHMAD',
    address:
      'JL. DIPONEGORO NO.2, SUMAHILANG, KEC. PEKANBARU KOTA, KOTA PEKANBARU, RIAU 28156',
    region: 'KOTA PEKANBARU, RIAU',
    phone: '(0761) 21618',
    province: 'Riau',
    maps: 'https://goo.gl/maps/RYCxuKuvFyNfCkR17',
  },
  {
    name: 'RS UMUM DAERAH  KOTA DUMAI',
    address:
      'JL. TJ. JATI NO.4, BULUH KASAP, DUMAI TIM., KOTA DUMAI, RIAU 28812',
    region: 'KOTA DUMAI, RIAU',
    phone: '(0765) 440992',
    province: 'Riau',
    maps: 'https://goo.gl/maps/WewzuExkmS3BuyvQ6',
  },
  {
    name: 'RS UMUM DAERAH  PURI HUSADA TEMBILAHAN',
    address:
      'JL. VETERAN NO.52, TEMBILAHAN HILIR, TEMBILAHAN, KABUPATEN INDRAGIRI HILIR, RIAU 29281',
    region: 'INDRAGIRI HILIR, RIAU',
    phone: '(0768) 22118',
    province: 'Riau',
    maps: 'https://goo.gl/maps/DxzyC8rcS2PQzYMh7',
  },
  {
    name: 'RS UMUM DAERAH PROVINSI SULAWESI BARAT',
    address:
      'JL. RE MARTADINATA, SIMBORO, KEC. SIMBORO DAN KEPULAUAN, KABUPATEN MAMUJU, SULAWESI BARAT 91512',
    region: 'MAMUJU, SULAWESI BARAT',
    phone: '(0426) 2703260',
    province: 'Sulawesi Barat',
    maps: 'https://goo.gl/maps/PDit8Kd9u3VS1FgT8',
  },
  {
    name: 'RSUP DR. WAHIDIN SUDIROHUSODO',
    address: 'JL. PERINTIS KEMERDEKAAN KM.11 MAKASAR',
    region: 'KOTA MAKASSAR, SULAWESI SELATAN',
    phone: '(0411) 584677',
    province: 'Sulawesi Selatan',
    maps: 'https://goo.gl/maps/Y2KMYdpoKEB56j659',
  },
  {
    name: 'RS DR. TADJUDDIN CHALID, MPH',
    address: 'JL. PACCERAKKANG NO.67 / PAJJAIANG DAYA MAKASSAR',
    region: 'KOTA MAKASSAR, SULAWESI SELATAN',
    phone: '(0411) 513795',
    province: 'Sulawesi Selatan',
    maps: 'https://goo.gl/maps/fBZkopy9SjJXWenW7',
  },
  {
    name: 'RS UMUM DAERAH LABUANG BAJI',
    address: 'JL. DR. RATULANGI NO.81 MAKASSAR',
    region: 'KOTA MAKASSAR, SULAWESI SELATAN',
    phone: '(0411) 873482',
    province: 'Sulawesi Selatan',
    maps: 'https://goo.gl/maps/ESYRpRbKcNvZP9q17',
  },
  {
    name: 'RS TK.II PELAMONIA',
    address: 'JL. JEND SUDIRMAN NO.27,MAKASSAR',
    region: 'KOTA MAKASSAR, SULAWESI SELATAN',
    phone: '0811-1782-399',
    province: 'Sulawesi Selatan',
    maps: 'https://goo.gl/maps/T5QnrD2zDnDuu5YHA',
  },
  {
    name: 'RS UMUM DAERAH LAKIPADADA',
    address: 'JL. PONGTIKU MANDETEK TANA TORAJA',
    region: 'TANA TORAJA, SULAWESI SELATAN',
    phone: '(0423) 22264',
    province: 'Sulawesi Selatan',
    maps: 'https://goo.gl/maps/EHmFzuKinFJ63ubu8',
  },
  {
    name: 'RS UMUM DAERAH KABUPATEN SINJAI',
    address: 'JL. JEND SUDIRMAN NO. 47 SINJAI, SULAWESI SELATAN',
    region: 'SINJAI, SULAWESI SELATAN',
    phone: '(0482) 21132',
    province: 'Sulawesi Selatan',
    maps: 'https://goo.gl/maps/3Q8AyTVxECN7yNrQ8',
  },
  {
    name: 'RS UMUM DAERAH ANDI MAKKASAU PAREPARE',
    address: 'JL. NURUSSAMAWATI NO.9 KOTA PAREPARE',
    region: 'KOTA PARE PARE, SULAWESI SELATAN',
    phone: '(0401) 27643',
    province: 'Sulawesi Selatan',
    maps: 'https://goo.gl/maps/w6zkMXQLgzD6fEMY9',
  },
  {
    name: 'RS UMUM DAERAH UNDATA PALU',
    address:
      'JALAN TRANS SULAWESI TONDO, TALISE, MANTIKULORE, KOTA PALU, SULAWESI TENGAH 94119',
    region: 'KOTA PALU, SULAWESI TENGAH',
    phone: '(0451) 4908020',
    province: 'Sulawesi Tengah',
    maps: 'https://goo.gl/maps/Y68V7Ca7bdopnCSC9',
  },
  {
    name: 'RS UMUM ANUTAPURA PALU',
    address: 'JL. KANGKUNG NO. 1 PALU',
    region: 'KOTA PALU, SULAWESI TENGAH',
    phone: '(0451) 460570',
    province: 'Sulawesi Tengah',
    maps: 'https://goo.gl/maps/CunnRzGjSTZ2p2JNA',
  },
  {
    name: 'RS UMUM  MOKOPIDO TOLI-TOLI',
    address: 'JL. LANONI NO.37 KEL BARU KEC BAOLAN KAB TOLI-TOLI, SULTENG',
    region: 'TOLITOLI, SULAWESI TENGAH',
    phone: '(0453) 21301',
    province: 'Sulawesi Tengah',
    maps: 'https://goo.gl/maps/U3s7q9dPRwMZuTVt6',
  },
  {
    name: 'RS UMUM DAERAH KOLONEDALE',
    address: 'JL. W MONGINSIDI 2 KOLONEDALE',
    region: 'MOROWALI UTARA, SULAWESI TENGAH',
    phone: '(0465) 21010',
    province: 'Sulawesi Tengah',
    maps: 'https://goo.gl/maps/9LFcRHsJbnsnExMi8',
  },
  {
    name: 'RS UMUM DAERAH KABUPATEN BANGGAI',
    address: 'JL. IMAM BONJOL KM 3 NO. 14 LUWUK',
    region: 'BANGGAI, SULAWESI TENGAH',
    phone: '(0461) 21820',
    province: 'Sulawesi Tengah',
    maps: 'https://goo.gl/maps/9yYx9Cy43ciySZ286',
  },
  {
    name: 'RS BAHTERAMAS PROVINSI SULTRA',
    address: 'JL. KAPTEN PIERE TENDEAN NO 50 KEC BARUGA',
    region: 'KOTA KENDARI, SULAWESI TENGGARA',
    phone: '(0401) 3195611',
    province: 'Sulawesi Tenggara',
    maps: 'https://goo.gl/maps/GPFRSp3hPeY8THqj7',
  },
  {
    name: 'RSUP PROF. DR. R. D. KANDOU',
    address: 'JL. RAYA TANAWANGKO NO.56, MANADO',
    region: 'KOTA MANADO, SULAWESI UTARA',
    phone: '(0431) 8383058',
    province: 'Sulawesi Utara',
    maps: 'https://goo.gl/maps/hq6E8fx5XTMhsWgo6',
  },
  {
    name: 'RS UMUM DR.SAM RATULANGI',
    address:
      'JL. R. SUPRAPTO NO.123, LUAAN, TONDANO TIM., KABUPATEN MINAHASA, SULAWESI UTARA',
    region: 'MINAHASA, SULAWESI UTARA',
    phone: '(0431) 321171',
    province: 'Sulawesi Utara',
    maps: 'https://goo.gl/maps/dKdoKijLv1BtcRY57',
  },
  {
    name: 'RSU RATATOTOK - BUYAT',
    address: 'JL. J.W. LASUT RATATOTOK II KECAMATAN RATATOTOK',
    region: 'MINAHASA TENGGARA, SULAWESI UTARA',
    phone: null,
    province: 'Sulawesi Utara',
    maps: 'https://goo.gl/maps/jxCUE4rUsfYkUsoC7',
  },
  {
    name: 'RS UMUM DAERAH KOTA KOTAMOBAGU',
    address: 'KELURAHAN POBUNDAYAN KECAMATAN KOTAMOBAGU SELATAN',
    region: 'KOTA KOTAMOBAGU, SULAWESI UTARA',
    phone: null,
    province: 'Sulawesi Utara',
    maps: 'https://goo.gl/maps/MUSrKcNfW8VeVJg1A',
  },
  {
    name: 'RSUP DR. M. DJAMIL',
    address: 'JL. PERINTIS KEMERDEKAAN PADANG',
    region: 'KOTA PADANG, SUMATERA BARAT',
    phone: null,
    province: 'Sumatera Barat',
    maps: 'https://goo.gl/maps/XWWqWS1zDcK8qW1PA',
  },
  {
    name: 'RS UMUM DAERAH DR. ACHMAD MOCHTAR',
    address:
      'JL. DR. ABDUL RIVAI NO.1, BUKIT APIT PUHUN, KEC. GUGUK PANJANG, KOTA BUKITTINGGI, SUMATERA BARAT 26122',
    region: 'KOTA BUKITTINGGI, SUMATERA BARAT',
    phone: '(0752) 21720',
    province: 'Sumatera Barat',
    maps: 'https://g.page/DesiHafshahOlshop20?share',
  },
  {
    name: 'RS UMUM DAERAH SITI FATIMAH PROVINSI SUMATERA SELATAN',
    address: 'JL. KOL. H. BURLIAN KM 6',
    region: 'KOTA PALEMBANG, SUMATERA SELATAN',
    phone: '(0711) 5718883',
    province: 'Sumatera Selatan',
    maps: 'https://goo.gl/maps/r3UXyGYpXi65N6iZA',
  },
  {
    name: 'RS UMUM PUSAT DR. MOHAMMAD HOESIN PALEMBANG',
    address:
      'JL. JEND. SUDIRMAN NO.KM.3,5, SEKIP JAYA, KEC. KEMUNING, KOTA PALEMBANG, SUMATERA SELATAN 30126',
    region: 'KOTA PALEMBANG, SUMATERA SELATAN',
    phone: '(0711) 354088',
    province: 'Sumatera Selatan',
    maps: 'https://goo.gl/maps/Ucu8BoVB2VLaRw6T6',
  },
  {
    name: 'RS UMUM DAERAH LAHAT',
    address: 'JL. LETJEND HARUN SOHAR NO.28',
    region: 'LAHAT, SUMATERA SELATAN',
    phone: null,
    province: 'Sumatera Selatan',
    maps: 'https://goo.gl/maps/dzPiWTDx9f9kakv76',
  },
  {
    name: 'RS DR. RIVAI ABDULLAH',
    address: 'JL. SUNGAI KUNDUR KELURAHAN MARIANA KEC. BANYUASIN I',
    region: 'BANYUASIN, SUMATERA SELATAN',
    phone: null,
    province: 'Sumatera Selatan',
    maps: 'https://goo.gl/maps/6ZDuwGNt9qzorvhj7',
  },
  {
    name: 'RS UMUM DAERAH KAYUAGUNG',
    address:
      'JL. LINTAS TIMUR LAMPUNG - PALEMBANG, JUA JUA, KEC. KAYU AGUNG, KABUPATEN OGAN KOMERING ILIR, SUMATERA SELATAN 30867',
    region: 'OGAN KOMERING ILIR, SUMATERA SELATAN',
    phone: '(0712) 323889',
    province: 'Sumatera Selatan',
    maps: 'https://goo.gl/maps/BfySrAbyFzwUXGkF6',
  },
  {
    name: 'RSUP H. ADAM MALIK',
    address:
      'JL. BUNGA LAU NO.17, KEMENANGAN TANI, KEC. MEDAN TUNTUNGAN, KOTA MEDAN, SUMATERA UTARA 20136',
    region: 'KOTA MEDAN, SUMATERA UTARA',
    phone: null,
    province: 'Sumatera Utara',
    maps: 'https://goo.gl/maps/UpfXqp1e1oUT8Gzz6',
  },
  {
    name: 'RS UMUM DAERAH DR. DJASAMEN SARAGIH',
    address: 'JL SUTOMO NO. 230, PEMATANGSIANTAR',
    region: 'KOTA PEMATANGSIANTAR, SUMATERA UTARA',
    phone: '(0622) 22959',
    province: 'Sumatera Utara',
    maps: 'https://goo.gl/maps/n7fPK5yCW8ZsqLAeA',
  },
  {
    name: 'RS UMUM DAERAH KABANJAHE',
    address: 'JL KAPTEN SELAMAT KETAREN NO. 08 KABANJAHE',
    region: 'KARO, SUMATERA UTARA',
    phone: '0628-20012',
    province: 'Sumatera Utara',
    maps: 'https://goo.gl/maps/XULhDVfPuA8ggXWt6',
  },
  {
    name: 'RS UMUM DAERAH PADANG SIDEMPUAN',
    address: 'JL DR. F.L. TOBING NO. 10,PADANGSIDIMPUAN',
    region: 'KOTA PADANG SIDIMPUAN, SUMATERA UTARA',
    phone: '(0634) 21251',
    province: 'Sumatera Utara',
    maps: 'https://goo.gl/maps/wcUNAFDV4wDug57p6',
  },
  {
    name: 'RS UMUM DAERAH TARUTUNG',
    address: 'JL AGUS SALIM NO. 1 TARUTUNG',
    region: 'TAPANULI UTARA, SUMATERA UTARA',
    phone: '0633 - 21303',
    province: 'Sumatera Utara',
    maps: 'https://goo.gl/maps/TQEKc6N9UuREsVtC8',
  },
]
